main: buttondevteam.alipresents.AliPresents
name: AliPresents
version: 2.0.2

commands:
  alilink:
    description: creates wireless redstone
  cashmob:
    description: creates mobs
  cb:
    description: creates creative boundaries
  debug:
    description: debug commands
  flaircolouring:
    description: flaaairs
  fruit:
    description: fruits
  gpower:
    description: powerssss
  insurance:
    description: item block insurance
  magic:
    description: magic
  metrics:
    description: metrics system