main: alisolarflare.AliPresents
name: AliPresents
version: 2.0.1

commands:
  pressalilink:
    description: Presses an Ali Link pressalilink frequency
  setalilink:
    description: Creates an Ali Link setalilink frequency
  flairme:
    description: Activates the Flair Me Command. Ask Ali, she was fucking tired when writing this description
  gpower:
    description: Testing command for ghostie powers
  powerup:
    description: Official g-power command that activates the ghostie powerups
  powerdown:
    description: Offical g-power command that deactivates the ghostie powerups
  addToUHC:
    description: Adds a player to the UltraHardcore match
  startMatch:
    description: Starts an UltraHardcore match